"""
export_sql.py  --  generate db/seed.sql from the JSON "database" in ../data.

The JSON files stay the source of truth (the pipeline writes them); this turns
them into INSERT ... ON CONFLICT statements you can paste into the Supabase SQL
editor or pipe into psql. Re-run whenever the data changes.

    python db/export_sql.py        # writes db/seed.sql
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = Path(__file__).resolve().parent / "seed.sql"

_ISO_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def s(v) -> str:
    """Quote a string literal (or NULL)."""
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def i(v) -> str:
    return "NULL" if v is None else str(int(v))


def b(v) -> str:
    return "true" if v else "false"


def date(v) -> str:
    """Only emit a DATE for an ISO yyyy-mm-dd; anything else (incl. 'TBC') -> NULL."""
    return s(v) if (v and _ISO_DATE.match(str(v))) else "NULL"


def jsonb(obj) -> str:
    if obj is None:
        return "NULL"
    return "'" + json.dumps(obj, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def text_array(lst) -> str:
    if not lst:
        return "NULL"
    return "ARRAY[" + ", ".join(s(x) for x in lst) + "]::text[]"


def load(sub: str) -> list[tuple[str, dict]]:
    d = DATA / sub
    return [(p.stem, json.loads(p.read_text(encoding="utf-8"))) for p in sorted(d.glob("*.json"))]


def main() -> int:
    lines: list[str] = [
        "-- Generated by db/export_sql.py from ../data — do not edit by hand.",
        "-- Run schema.sql first. Idempotent via ON CONFLICT.",
        "begin;",
        "",
    ]

    # Fighters first (bouts FK them).
    lines.append("-- fighters")
    for fid, f in load("fighters"):
        snap = f.get("latest") or {}
        rec = snap.get("record", {})
        phys = snap.get("physical", {})
        meta = snap.get("_meta", {})
        lines.append(
            "insert into fighters (id, name, dob, wikipedia_title, has_wikipedia, "
            "wins, losses, draws, wins_ko, wins_dec, no_contests, age, stance, "
            "height_inches, reach_inches, weight_classes, latest_snapshot, updated_at) values ("
            f"{s(f.get('id', fid))}, {s(f.get('name'))}, {date(f.get('dob'))}, "
            f"{s(f.get('wikipediaTitle'))}, {b(f.get('hasWikipedia'))}, "
            f"{i(rec.get('wins'))}, {i(rec.get('losses'))}, {i(rec.get('draws'))}, "
            f"{i(rec.get('winsKo'))}, {i(rec.get('winsDec'))}, {i(rec.get('noContests'))}, "
            f"{i(phys.get('age'))}, {s(phys.get('stance'))}, "
            f"{i(phys.get('heightInches'))}, {i(phys.get('reachInches'))}, "
            f"{text_array(meta.get('weightClasses'))}, {jsonb(snap)}, "
            f"coalesce({s(f.get('updatedAt'))}::timestamptz, now()))\n"
            "on conflict (id) do update set name=excluded.name, dob=excluded.dob, "
            "wikipedia_title=excluded.wikipedia_title, has_wikipedia=excluded.has_wikipedia, "
            "wins=excluded.wins, losses=excluded.losses, draws=excluded.draws, "
            "wins_ko=excluded.wins_ko, wins_dec=excluded.wins_dec, no_contests=excluded.no_contests, "
            "age=excluded.age, stance=excluded.stance, height_inches=excluded.height_inches, "
            "reach_inches=excluded.reach_inches, weight_classes=excluded.weight_classes, "
            "latest_snapshot=excluded.latest_snapshot, updated_at=excluded.updated_at;"
        )

    # Bouts.
    bout_slugs: set[str] = set()
    lines += ["", "-- bouts"]
    for slug, pkg in load("packages"):
        bout = pkg.get("bout", {})
        if not (bout.get("fighterAId") and bout.get("fighterBId")):
            print(f"[skip] {slug}: missing fighter ids")
            continue
        bout_slugs.add(slug)
        prompt = {"system": pkg.get("system_prompt"), "user": pkg.get("user_prompt"),
                  "model": pkg.get("model")}
        lines.append(
            "insert into bouts (slug, fighter_a_id, fighter_b_id, weight_class, event_date, "
            "announced_at, headline, source, source_url, fighter_a_snapshot, fighter_b_snapshot, prompt) values ("
            f"{s(slug)}, {s(bout.get('fighterAId'))}, {s(bout.get('fighterBId'))}, "
            f"{s(bout.get('weightClass'))}, {date(bout.get('eventDate'))}, "
            f"{s(bout.get('announcedAt'))}, {s(bout.get('headline'))}, {s(bout.get('source'))}, "
            f"{s(bout.get('link'))}, {jsonb(pkg.get('fighter_a_snapshot'))}, "
            f"{jsonb(pkg.get('fighter_b_snapshot'))}, {jsonb(prompt)})\n"
            "on conflict (slug) do update set fighter_a_id=excluded.fighter_a_id, "
            "fighter_b_id=excluded.fighter_b_id, weight_class=excluded.weight_class, "
            "event_date=excluded.event_date, announced_at=excluded.announced_at, "
            "headline=excluded.headline, source=excluded.source, source_url=excluded.source_url, "
            "fighter_a_snapshot=excluded.fighter_a_snapshot, "
            "fighter_b_snapshot=excluded.fighter_b_snapshot, prompt=excluded.prompt;"
        )

    # Articles last (FK bouts) — only those whose bout was emitted.
    lines += ["", "-- articles"]
    for slug, art in load("articles"):
        if slug not in bout_slugs:
            print(f"[skip] article {slug}: no matching bout")
            continue
        lines.append(
            "insert into articles (slug, title, summary, body, tags, ai_generated) values ("
            f"{s(art.get('slug', slug))}, {s(art.get('title'))}, {s(art.get('summary'))}, "
            f"{s(art.get('body'))}, {text_array(art.get('tags'))}, {b(art.get('ai_generated', True))})\n"
            "on conflict (slug) do update set title=excluded.title, summary=excluded.summary, "
            "body=excluded.body, tags=excluded.tags, ai_generated=excluded.ai_generated;"
        )

    lines += ["", "commit;", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
